export enum Rutas {
  HOME = '',
  NOT_FOUND = '**',
  DASHBOARD = 'tablero',
  PROJECTS = 'proyectos',
  EXPERIENCES = 'experiencias',
  NEW_ROUTES = 'nueva',
  NEW_ROUTES_O = 'nuevo',
  UPDATE_ROUTES = 'actualizar',
  SUBSCRIBERS = 'subscriptores',
  CONTACTS = 'contactos',
  AUDITS = 'auditorias',
  PROFILE = 'perfil',
  SETTINGS = 'configuraciones',
}
